2018-06-13 11:36:49,812-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 11:36:49,812-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 11:38:04,332-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 11:38:04,332-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 11:55:37,004-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8466DE01-9128-4AA7-84B3-70964EDCF29D
2018-06-13 11:55:40,008-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6AB6695E-44EA-4569-92F7-946B365F88A1
2018-06-13 11:56:51,813-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 11:56:51,813-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 11:56:53,263-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 86E866A2-D562-4C9A-B62C-4E79CC184F25
2018-06-13 11:56:55,518-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F692E711-D544-43C7-8FBD-A6BEDBE3C3F0
2018-06-13 11:58:09,305-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 11:58:09,306-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 12:07:02,694-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/sqlmanager/tasks.py-[line:81]-SQLRollBackModel 创建对象失败,错误信息: Cannot force an update in save() with no primary key.
2018-06-13 12:15:37,073-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 57AB6728-361E-40C4-A1D3-FCFAAB7B1214
2018-06-13 12:15:38,905-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 7E6A6279-2FA2-4C68-B29F-25AAF449FF7E
2018-06-13 12:16:55,370-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 12:16:55,370-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 12:16:56,951-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 543827C6-7888-4396-9B63-CFDB10341438
2018-06-13 12:16:58,021-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 43B9EE10-94F4-47BF-B961-CA33E1971DB1
2018-06-13 12:18:09,840-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 12:18:09,840-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 12:35:36,993-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 520A4CBA-2EA1-4C41-87CD-F3179B06D2E0
2018-06-13 12:35:38,798-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: FA7E1BDF-EC91-4AAD-83A9-238EB9F5579E
2018-06-13 12:36:54,271-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 12:36:54,272-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 12:36:55,900-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: EE158D84-8379-4332-9FFC-959062D36783
2018-06-13 12:36:57,127-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 0DBFEC0A-F463-47B0-B9AC-AA372B28D23F
2018-06-13 12:38:08,744-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 12:38:08,744-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 12:55:37,130-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 9B681EA1-9001-4F90-97DD-5AA4E0BB7E99
2018-06-13 12:55:38,892-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: EF9824ED-AC1A-4D1F-8A8F-8A698F50BA53
2018-06-13 12:56:53,712-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 12:56:53,712-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 12:56:55,337-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8BD1D90F-6948-43A5-9BDF-E9AC128FE4EB
2018-06-13 12:56:56,660-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8DEC876A-117F-44F1-B60B-299B03668D93
2018-06-13 12:58:09,509-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 12:58:09,509-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 13:15:36,991-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 46EA69C9-D136-44BC-923A-217480A34D0E
2018-06-13 13:15:38,837-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: D6B3B751-811C-49B6-930F-C3EAED7062E1
2018-06-13 13:16:54,163-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 13:16:54,164-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 13:16:55,695-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 3FC3ECBC-EA50-43D3-93B9-BCAC6849A136
2018-06-13 13:16:57,001-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 81D1EDED-56A5-403D-95D1-6BB88E1BF639
2018-06-13 13:18:08,979-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 13:18:08,979-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 13:35:36,975-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8BDFC192-1987-4F33-A642-2190BE316DED
2018-06-13 13:35:38,833-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 2287E5C9-6231-48F6-940C-000C147B1A68
2018-06-13 13:36:56,389-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 13:36:56,389-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 13:36:57,896-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 3CDB8228-3695-4939-A863-55DCAFF39281
2018-06-13 13:36:58,984-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F25D9C03-D4F8-4752-9C4E-7B755AAA9174
2018-06-13 13:38:10,332-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 13:38:10,333-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 13:55:37,206-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C8DC10E7-C219-41AC-9322-2830A16948B3
2018-06-13 13:55:39,056-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F3E06B34-ED52-44C9-A49D-D4DEFD658090
2018-06-13 13:56:53,104-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 13:56:53,104-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 13:56:54,665-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 562A7753-00EE-4446-A14F-58C509103CEE
2018-06-13 13:56:55,912-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 858F51E3-0C92-4B53-81CA-078400E22413
2018-06-13 13:58:10,015-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 13:58:10,016-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 14:15:37,009-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 276588F6-F328-4B53-9C88-6065273452B4
2018-06-13 14:15:38,688-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8490D93F-C51C-4F76-BCA5-578F972F3D0C
2018-06-13 14:16:56,464-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 14:16:56,464-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 14:16:58,095-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: FCD7367E-9166-42EB-AFD0-203902E53510
2018-06-13 14:16:59,340-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 7CC52770-E06D-485F-99E6-05D2A1637DD9
2018-06-13 14:18:11,171-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 14:18:11,171-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 14:35:36,925-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 95394A4B-2505-4854-80BD-496ABD6805C4
2018-06-13 14:35:38,790-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 0C9D72A7-BD85-4B8E-A65A-3FB91DF7963B
2018-06-13 14:36:57,349-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 14:36:57,349-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 14:36:58,761-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: B0ED6B75-EBA3-49E8-AC7E-1762811DF661
2018-06-13 14:36:59,885-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 88159F63-E3BF-44A3-8E13-5723288F4C90
2018-06-13 14:38:12,005-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 14:38:12,005-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 14:55:37,006-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: CEB18E1C-1CE4-4E1F-9BB3-368A2B905F26
2018-06-13 14:55:38,931-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 5D32D9FD-8DD7-4DFE-AA04-A43D39FC01D0
2018-06-13 14:56:52,864-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 14:56:52,865-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 14:56:54,408-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 175F1CF8-D960-44AC-95BC-5C44840662DD
2018-06-13 14:56:56,607-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 7C665689-1946-4863-9C0C-45BB521497BD
2018-06-13 14:58:09,624-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 14:58:09,624-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 15:15:37,005-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 28D34AB0-B633-4B6A-BE4D-961944DB440B
2018-06-13 15:15:38,900-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: A77C2C3E-9168-4A7F-9CDD-ACEBFBCA1A9C
2018-06-13 15:16:57,060-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 15:16:57,061-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 15:16:58,960-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 56255EA1-6D76-45FE-918F-8E7C056F9990
2018-06-13 15:17:00,094-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 2DD9D17C-5D96-4A0D-9A97-58495706D8D2
2018-06-13 15:18:13,171-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 15:18:13,171-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 15:35:37,042-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 56D9734C-83BC-4DF8-83D2-A4078A1D072C
2018-06-13 15:35:40,081-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: AE3906D2-B544-4820-80EC-43AE1726C4B8
2018-06-13 15:36:57,164-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 15:36:57,164-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 15:36:58,754-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 3FC96AB4-E2E5-4BC9-AF46-354957D1557E
2018-06-13 15:36:59,855-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 0A1CFB87-A849-47A0-BD97-8657FA71D7CE
2018-06-13 15:38:11,922-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 15:38:11,922-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 15:55:36,979-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 2C9651DA-D90E-4B46-AED3-64A1C13B55C8
2018-06-13 15:55:38,776-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C9C15746-C22C-4AA0-B56C-3FF243492BD0
2018-06-13 15:56:54,162-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 15:56:54,162-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 15:56:55,696-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 881C2199-0D17-4D33-B10A-73E596B08F6D
2018-06-13 15:56:57,012-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 601FAB4A-5A8C-48B7-9C7A-4F7B25E910D6
2018-06-13 15:58:10,028-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 15:58:10,028-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 16:15:36,994-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 96F46884-D983-4957-830D-FD250CFC7638
2018-06-13 16:15:38,905-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 295B2672-E690-489C-AAEF-0BBECBE49570
2018-06-13 16:16:56,889-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 16:16:56,889-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 16:16:58,430-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: E5904D04-9131-45F8-9D23-3409A5E76750
2018-06-13 16:16:59,561-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 77F10B4D-92DE-4493-8865-EA03DC38F7C9
2018-06-13 16:18:14,929-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 16:18:14,929-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 16:35:37,016-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6F0A3514-E300-4CD5-A071-88FB1C29105D
2018-06-13 16:35:39,850-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 75B6DB90-01B1-498F-ADC6-5B18FF08988A
2018-06-13 16:36:59,146-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 16:36:59,152-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 16:37:00,752-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: E7A53A30-F2E5-4599-96EC-6262AE628D97
2018-06-13 16:37:01,936-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 16AD882C-33D4-4098-A64E-E1D23EC620F9
2018-06-13 16:38:12,103-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 16:38:12,103-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 16:49:42,268-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/sqlmanager/inception_relate/__init__.py-[line:501]-SQLExecDetailModel 模型更新对象 id: 13 失败                                                 或者SQLRollBackModel 模型更新对象 id: 13 失败,错误信息: ("local variable 'sql_obj' referenced before assignment",)
2018-06-13 16:54:24,775-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/sqlmanager/inception_relate/__init__.py-[line:503]-SQLExecDetailModel 模型更新对象 id: 13 失败                                 或者SQLRollBackModel 模型更新对象 id: 13 失败,错误信息: ("local variable 'sql_obj' referenced before assignment",)
2018-06-13 16:55:37,019-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: DAF2BA96-BD7B-45C8-84DA-33261C46112C
2018-06-13 16:55:38,912-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: CB4107F7-E3F4-4B10-A7B4-D618AC5277CD
2018-06-13 16:57:01,541-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 16:57:01,541-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 16:57:03,049-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: A58EB100-063B-4D06-8881-C1A5C375374F
2018-06-13 16:57:04,561-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 153ABB3F-4227-49BF-817F-C5ADFD2AF1F4
2018-06-13 16:58:14,012-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 16:58:14,013-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 17:15:37,160-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C979C259-2383-4E41-8B0C-4D2ACB6B79A6
2018-06-13 17:15:39,086-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 7DEE5E80-F075-4347-9812-D1AA0DFA9306
2018-06-13 17:16:56,316-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 17:16:56,316-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 17:16:57,823-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 993788ED-2969-4188-BDB9-56826AF7B9C8
2018-06-13 17:16:58,984-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: BF9951D9-FD5D-457D-88C0-957C2FB278F3
2018-06-13 17:18:12,093-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 17:18:12,094-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 17:35:36,927-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 615FFB9D-74E4-48C4-93D4-33FD3E86D73F
2018-06-13 17:35:38,742-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: AF4742E7-6C61-4F5C-BB5E-A20C8497126C
2018-06-13 17:36:55,341-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 17:36:55,342-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 17:36:56,812-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 9A75F23F-FBFF-4326-8EEB-30C6769C12D7
2018-06-13 17:36:58,190-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 457777B0-5081-4582-B612-B0A7C3EDDDBE
2018-06-13 17:38:12,580-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 17:38:12,581-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 17:55:36,945-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F349D5DE-2D6D-4107-8953-5256E156D00B
2018-06-13 17:55:38,874-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8A938D7A-9011-4BCE-A0BC-09AC7774A3C6
2018-06-13 17:56:54,550-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 17:56:54,550-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 17:56:56,197-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C6B3D158-5A39-497B-9169-DBCB7F6433A8
2018-06-13 17:56:57,492-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 87810885-DDB2-446C-AAAE-EF01353FA103
2018-06-13 17:58:09,611-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 17:58:09,612-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 18:15:37,029-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6C7D4D98-C791-4A2E-A23D-78A07EC61543
2018-06-13 18:15:38,816-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C232518D-9B6A-4306-9FF0-50774B8D0609
2018-06-13 18:16:56,396-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 18:16:56,396-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 18:16:57,902-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: D3B56E03-060F-4383-B141-C2A2D3572105
2018-06-13 18:16:59,968-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 585B96D8-0A64-4495-BAAF-7E88C28DADEA
2018-06-13 18:18:12,606-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 18:18:12,607-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 18:35:37,145-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4A76225B-D845-498C-98A3-64A3CEC960CD
2018-06-13 18:35:38,967-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 3510C8D3-73DB-42B3-B482-34C6C5394450
2018-06-13 18:36:53,406-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 18:36:53,407-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 18:36:54,924-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C96E0BF1-A044-44C1-BEA7-A1A8E31E27FC
2018-06-13 18:36:56,272-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 2209D3D3-BD7F-4281-B570-D4D7E171CE49
2018-06-13 18:38:10,076-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 18:38:10,076-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 18:55:36,947-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 591D6B0A-3167-473E-BDC6-6AFAB58EE7F9
2018-06-13 18:55:38,731-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: B2B99144-F58D-4EDD-9963-6CB13CB75A8D
2018-06-13 18:56:54,195-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 18:56:54,195-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 18:56:55,694-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: EB1B7C72-7A24-4EA0-B1AC-D74D97191121
2018-06-13 18:56:58,075-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 023D5CA4-B679-4E18-8482-AD4C92B111C4
2018-06-13 18:58:10,006-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 18:58:10,006-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 19:15:36,904-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 0336EFE5-53D0-4EDB-BDDE-EE4DB5AC7248
2018-06-13 19:15:38,775-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 57BFFB0B-7E37-4AF4-9C29-4C0CAE0264C4
2018-06-13 19:16:52,997-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 19:16:52,997-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 19:16:54,464-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: AFA508E6-AF23-4690-AAA1-4013F358C6F7
2018-06-13 19:16:55,775-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: B46CC575-FA00-4564-9EDD-2C464BDD7174
2018-06-13 19:18:09,425-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 19:18:09,425-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 19:35:36,914-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 19F5F47B-E960-4ACE-8DB2-D2BBB8A20923
2018-06-13 19:35:38,735-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: E28ED7A4-CD37-4ED1-9471-C3360DBF3197
2018-06-13 19:36:53,914-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 19:36:53,914-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 19:36:55,783-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: A661DF69-E760-4567-9580-92FCCFBACE0A
2018-06-13 19:36:57,108-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 20ACB953-F758-4465-9D8B-EE13E8A63592
2018-06-13 19:38:11,526-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 19:38:11,527-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 19:50:43,749-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/sqlmanager/tasks.py-[line:55]-SQLExecDetailModel 对象 id: 30 备份失败或不需要备份,因此不需要查询备份语句
2018-06-13 19:55:37,099-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 1C373F20-0CFE-43FC-A01B-B8BFDC388C7B
2018-06-13 19:55:38,930-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4D6B460A-B312-4C13-B0F9-0B3D3B70C1B6
2018-06-13 19:56:51,428-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 19:56:51,428-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 19:56:52,913-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 312D4465-3CF7-459A-B266-B659DD73C5F3
2018-06-13 19:56:54,102-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C5C09A0C-39A3-46AF-8966-C0A55F9419A6
2018-06-13 19:58:08,424-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 19:58:08,425-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 20:15:37,119-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F905871C-A1C7-4698-B83E-94BCB936CE77
2018-06-13 20:15:39,079-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 1DB7AC96-8D48-4BEA-B332-BFCE1DE01852
2018-06-13 20:16:55,319-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 20:16:55,319-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 20:16:56,840-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8876B1A4-F658-4CC7-A3E5-344EE8B2F247
2018-06-13 20:16:58,170-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 9AE59436-D7D1-426C-832F-5F896B77E27D
2018-06-13 20:18:11,687-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 20:18:11,688-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 20:35:37,088-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: A84089D8-D284-4A25-A21A-68BEEF5D0678
2018-06-13 20:35:39,016-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4866845C-9B9A-4DEB-8651-2A32C15BEBA4
2018-06-13 20:36:53,558-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 20:36:53,558-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 20:36:55,187-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 84858DBB-DC46-432E-8C0F-2B57940AAE2F
2018-06-13 20:36:56,463-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: DE618942-4EB6-4A21-A6A2-C1E04D43FA48
2018-06-13 20:38:09,866-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 20:38:09,866-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 20:55:37,107-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 20AD28A9-96F0-49D5-8AC6-A804ADDA3EE4
2018-06-13 20:55:39,004-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 459541C2-C77C-44FF-B3F9-29AC561BFDEE
2018-06-13 20:56:52,863-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 20:56:52,863-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 20:56:54,909-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F57D209C-46C3-4C9F-97F7-25F37F347E89
2018-06-13 20:56:56,117-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C4B30ABD-53A7-4395-9E2C-601966470BE4
2018-06-13 20:58:09,150-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 20:58:09,150-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 21:05:49,403-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:427]-自动添加服务器: 172.17.135.18,错误信息: (1062, "Duplicate entry '172.17.135.18' for key 'private_ip'")
2018-06-13 21:05:49,405-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:427]-自动添加服务器: 172.17.135.21,错误信息: (1062, "Duplicate entry '172.17.135.21' for key 'private_ip'")
2018-06-13 21:05:49,407-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:427]-自动添加服务器: 172.17.135.20,错误信息: (1062, "Duplicate entry '172.17.135.20' for key 'private_ip'")
2018-06-13 21:05:49,411-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:427]-自动添加服务器: 172.17.135.19,错误信息: (1062, "Duplicate entry '172.17.135.19' for key 'private_ip'")
2018-06-13 21:15:37,124-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: CA5912AF-D022-4368-B6A6-E5B9D3A4B882
2018-06-13 21:15:39,158-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 5A7A3A45-BFD6-4F20-88B1-59527AEC7DFA
2018-06-13 21:15:40,416-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 056F113D-C0A8-4AC1-BAFE-D860D86112A9
2018-06-13 21:15:41,700-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 9D0C21D5-4BDD-49D8-963F-36783CEB3E99
2018-06-13 21:16:55,167-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 21:16:55,167-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 21:16:56,723-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 118612E1-BEBA-4D16-8F31-164567C4993D
2018-06-13 21:16:57,883-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8E85C59D-CC3D-4887-95BD-FA3F0E5978B9
2018-06-13 21:16:59,058-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8EAA8AEB-42D5-47AA-B66A-EB329CE70156
2018-06-13 21:17:00,174-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4900B563-5F94-4FE3-918B-EC0BAFC6C330
2018-06-13 21:18:11,814-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 21:18:11,815-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-06-13 21:35:37,108-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: E64A1E81-5EC4-4E18-9F94-E53A7575DD0E
2018-06-13 21:35:38,933-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6EBC7C76-B6E9-45A2-A52E-F08E2459D8B9
2018-06-13 21:35:40,145-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 02DD15CD-F4A0-4FE1-861E-D081112E4B2A
2018-06-13 21:35:41,437-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 617F76EE-9F86-46CC-B3EA-19A5116820B2
2018-06-13 21:36:58,141-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/server/__init__.py-[line:89]-("'ResultCallback' object has no attribute 'data'",)
2018-06-13 21:36:58,141-[ERROR]-/ops-data/zp/haha/dev-mysite/opsweb/resources/tasks.py-[line:39]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
