2018-03-28 00:00:26,371-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 3AFBDA14-438B-49C5-9629-698C2964298A
2018-03-28 00:00:57,888-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:00:57,889-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:01:39,463-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:01:39,463-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:10:15,735-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 76A83201-1B90-4FAB-B1AE-C54CC85F4697
2018-03-28 00:10:48,684-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:10:48,685-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:11:27,324-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:11:27,325-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:15:03,014-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 00:15:03,202-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 00:15:03,340-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 00:15:03,397-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 00:20:16,423-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 082BB33C-B9F0-402F-B1D1-1F18EAA64882
2018-03-28 00:20:50,841-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:20:50,841-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:21:31,135-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:21:31,136-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:30:05,435-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 00:30:05,854-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 00:30:06,139-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 00:30:06,312-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 00:30:17,795-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: DB16492A-D30E-49CC-AB53-EA9239EAEA5E
2018-03-28 00:30:49,132-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:30:49,133-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:31:29,309-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:31:29,309-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:40:16,204-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 65B54E4A-6583-402C-9F01-E10A277A3D9F
2018-03-28 00:40:47,414-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:40:47,414-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:41:26,952-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:41:26,952-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:45:02,984-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 00:45:03,198-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 00:45:03,340-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 00:45:03,389-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 00:50:09,827-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 0A098C83-E24A-4538-9DAA-14F7DCF15E78
2018-03-28 00:50:09,828-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 00:50:12,793-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 2AC4CC18-FB8B-4BE5-9BB9-FBE1E65DFE9B
2018-03-28 00:50:45,712-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:50:45,712-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 00:50:48,367-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: D5DE046F-8D3B-4F93-99CC-D8E877D4567A
2018-03-28 00:50:48,368-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 00:50:53,264-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 9BB75B6F-B624-44A4-9469-35116F9FE505
2018-03-28 00:50:53,265-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 00:51:18,086-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 00:51:18,086-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:00:04,030-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 01:00:04,216-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 01:00:04,424-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 01:00:04,468-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 01:00:14,500-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 8BF37F99-A06C-4079-845B-225AC2323576
2018-03-28 01:00:14,500-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:00:20,326-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 35FD16B3-7BF2-4B06-9A76-C6D9A863B922
2018-03-28 01:00:53,349-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:00:53,350-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:00:55,925-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: DD38911C-F291-4426-B8F3-E3882366E5B4
2018-03-28 01:00:55,925-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:01:00,921-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B96EF332-4CA8-42F0-9FF0-058F09407B82
2018-03-28 01:01:00,922-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:01:26,982-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:01:26,982-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:10:09,843-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 3F022561-09BF-4645-B4B7-50C99988F40D
2018-03-28 01:10:09,843-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:10:12,771-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 7A864B5F-DB67-47C5-A626-C1BF02176955
2018-03-28 01:10:43,713-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:10:43,713-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:10:46,395-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 3C43BF20-355C-4CA4-80C0-1FA49A6DC893
2018-03-28 01:10:46,395-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:10:51,489-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A68C43D0-817B-4DBC-A25A-81D458BA6329
2018-03-28 01:10:51,489-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:11:15,957-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:11:15,957-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:15:02,929-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 01:15:03,133-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 01:15:03,279-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 01:15:03,338-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 01:20:10,180-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A01249CF-2A72-404A-8B9E-5FD2FD150587
2018-03-28 01:20:10,181-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:20:13,155-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4A1505F5-9951-48B4-B0B3-CC01758A3354
2018-03-28 01:20:44,218-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:20:44,219-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:20:46,916-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 351EA257-60BC-4850-BCE9-2BB587DB0B65
2018-03-28 01:20:46,916-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:20:52,573-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 2B008220-C78C-49DD-AE84-87343A0CBA1B
2018-03-28 01:20:52,573-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:21:17,816-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:21:17,817-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:30:05,260-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 01:30:05,564-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 01:30:05,707-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 01:30:05,766-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 01:30:11,385-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 3DDBE266-40C8-4C5F-A1FF-743B2144353E
2018-03-28 01:30:11,386-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:30:14,261-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C2C975EE-D396-4BE7-B4BA-40D77D1C81E8
2018-03-28 01:30:45,759-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:30:45,759-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:30:48,263-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 456DB124-C4A8-4EF0-9F13-B74A0BFBB6A7
2018-03-28 01:30:48,263-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:30:53,327-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 1C84AD18-B0D1-4256-AC31-1AC2C42D0621
2018-03-28 01:30:53,327-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:31:17,940-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:31:17,941-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:40:09,275-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 6A1BAF6A-A6FF-4E99-8C94-7838F6BF4768
2018-03-28 01:40:09,275-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:40:12,092-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 55918CCD-C728-4115-AB4F-2929FF496909
2018-03-28 01:40:44,611-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:40:44,612-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:40:47,348-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 88C8F6EF-91E5-462F-ACB4-DEC6DFDF1AE4
2018-03-28 01:40:47,348-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:40:52,219-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E994690F-857D-4FF3-A31E-FF14B467B58E
2018-03-28 01:40:52,219-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:41:16,605-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:41:16,605-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:45:03,135-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 01:45:03,365-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 01:45:03,499-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 01:45:03,557-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 01:50:08,080-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 63F7CA96-2D02-4460-BB1B-46C8D9059BE8
2018-03-28 01:50:08,080-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:50:11,099-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 5A260AC4-EBDE-4D7B-A9FB-819BC849237B
2018-03-28 01:50:42,622-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:50:42,623-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 01:50:45,111-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: EA1D48E2-3E39-4EB7-A04C-C206CF73E71D
2018-03-28 01:50:45,111-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:50:51,209-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 46766054-30E3-48FA-B213-7029B52EA72B
2018-03-28 01:50:51,210-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 01:51:15,752-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 01:51:15,752-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:00:04,871-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 02:00:05,247-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 02:00:05,503-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 02:00:05,578-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 02:00:19,774-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 24731C1D-CD8E-4A09-8B06-A03112000938
2018-03-28 02:00:19,775-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:00:22,562-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: D56C9E2F-E758-4923-AEC8-F4E99947B116
2018-03-28 02:00:56,964-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:00:56,965-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:01:02,384-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 9EB88CA3-C7CF-4606-9355-B7C396E4C440
2018-03-28 02:01:02,384-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:01:07,516-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F9E1DFE0-9E34-4C6F-9329-568DF96C9F51
2018-03-28 02:01:07,516-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:01:32,975-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:01:32,976-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:10:09,093-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 1A86B496-39A4-4539-9C4B-29E1AC0892BA
2018-03-28 02:10:09,093-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:10:12,049-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 34A1A48B-4198-4656-A77C-D800A2F7D177
2018-03-28 02:10:43,136-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:10:43,137-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:10:45,833-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 83127AD1-873F-4E74-94DB-EB9147F9B0CE
2018-03-28 02:10:45,833-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:10:50,908-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 683A8D2A-AD40-4953-A202-82D61F40A64F
2018-03-28 02:10:50,908-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:11:16,034-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:11:16,035-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:15:03,116-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 02:15:03,290-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 02:15:03,412-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 02:15:03,458-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 02:20:10,176-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E7132FA2-5F1B-43AE-AE26-448195AE721D
2018-03-28 02:20:10,176-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:20:13,651-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 501EB117-8C47-4CD5-8A2D-86BB2B2D95F5
2018-03-28 02:20:45,841-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:20:45,842-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:20:48,607-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 1E089B04-FF0D-4181-809D-4BE777E277F5
2018-03-28 02:20:48,608-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:20:54,877-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 8DA0674D-728B-48EB-AE81-E033F6727D5E
2018-03-28 02:20:54,877-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:21:19,845-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:21:19,845-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:30:05,844-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 02:30:06,199-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 02:30:06,525-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 02:30:06,622-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 02:30:11,414-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A673A560-76B6-4305-91DF-E4F388E10368
2018-03-28 02:30:11,414-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:30:15,266-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: FC0DDD52-BC85-4E1A-8888-0F0203D1D1D6
2018-03-28 02:30:50,776-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:30:50,777-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:30:53,479-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A8E32A5D-DE40-42FE-A0BF-BA8EB197C14A
2018-03-28 02:30:53,479-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:30:58,296-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A168BC65-A48E-463C-A0C2-1F91D9BE3AF5
2018-03-28 02:30:58,296-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:31:25,683-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:31:25,683-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:40:08,836-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: CF323033-27EA-4823-8C6E-315429B3055D
2018-03-28 02:40:08,837-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:40:11,652-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8FECB96E-7596-4C57-A6B2-01F1C4E5D42F
2018-03-28 02:40:42,050-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:40:42,051-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:40:44,685-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: BB54595E-6411-4C9B-8E64-F8EA1CFAE893
2018-03-28 02:40:44,685-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:40:49,723-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 00FF44C7-263F-4F89-B3D4-D005D2DC10CD
2018-03-28 02:40:49,724-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:41:14,837-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:41:14,838-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:45:02,942-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 02:45:03,179-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 02:45:03,347-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 02:45:03,395-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 02:50:08,599-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 4E048BDE-5B68-44F4-8470-AFACB16315C6
2018-03-28 02:50:08,599-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:50:11,569-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: D30387B3-6F80-427E-BF44-88F6771A5B4A
2018-03-28 02:50:42,906-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:50:42,906-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 02:50:45,482-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 36368434-0881-4157-B4D2-2C48DCCD4644
2018-03-28 02:50:45,483-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:50:50,869-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 99343D07-D8F9-4D13-8BAD-491E9C32FE14
2018-03-28 02:50:50,869-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 02:51:14,483-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 02:51:14,483-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:00:05,455-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 03:00:05,709-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 03:00:05,977-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 03:00:06,077-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 03:00:10,764-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 27AB9B5E-50DB-4939-8052-E020DBB3A602
2018-03-28 03:00:10,764-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:00:13,562-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4E8598DB-B71C-446B-A258-1DE6715E8A74
2018-03-28 03:00:44,610-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:00:44,610-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:00:47,379-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: CA3B8F33-1184-4065-90B3-0A39290BF87C
2018-03-28 03:00:47,379-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:00:52,522-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: BDEB210C-55C9-4894-BC34-22BF430CA434
2018-03-28 03:00:52,523-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:01:17,425-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:01:17,426-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:10:08,980-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 88EA361D-B77A-47E3-8F98-2436CA190A98
2018-03-28 03:10:08,980-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:10:11,923-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F884CA48-22D3-4317-9664-39868E963367
2018-03-28 03:10:43,125-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:10:43,125-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:10:45,672-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: AAB3FF63-A1DA-45C5-82DB-77D6EEEB5188
2018-03-28 03:10:45,672-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:10:50,628-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A726DBE3-0F2E-49B6-AFB5-F6216B339ECC
2018-03-28 03:10:50,628-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:11:15,333-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:11:15,334-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:15:03,042-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 03:15:03,231-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 03:15:03,365-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 03:15:03,412-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 03:20:08,382-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 444BF631-21DD-4233-84B5-0AD0C1F30401
2018-03-28 03:20:08,382-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:20:11,119-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: A15E7DFA-75D3-4DE0-A316-7B30DE0362A9
2018-03-28 03:20:41,989-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:20:41,989-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:20:45,529-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B7344B49-5BD9-4D46-8790-969C7C8D2EFB
2018-03-28 03:20:45,529-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:20:50,437-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 74FF85D1-5796-4FB6-9A20-5863ED2EEFCD
2018-03-28 03:20:50,437-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:21:15,146-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:21:15,147-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:30:04,682-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 03:30:04,941-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 03:30:05,181-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 03:30:05,276-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 03:30:11,006-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: ACBEDB4A-FB89-43F2-A87D-D4775811E7E4
2018-03-28 03:30:11,006-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:30:14,057-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 66C841C1-01E3-4F10-9093-C13DC4797212
2018-03-28 03:30:45,176-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:30:45,176-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:30:47,712-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: EC1FBBDE-E8E7-4F6E-85E3-309C2687D010
2018-03-28 03:30:47,713-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:30:52,488-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: D6B8AE4A-CFB5-4065-9A0A-9FED67B3D865
2018-03-28 03:30:52,488-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:31:17,037-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:31:17,037-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:40:21,568-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 74076D84-2B27-4F5B-AA24-715A3A2A2FFC
2018-03-28 03:40:21,569-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:40:30,981-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 46CD4DD9-DF33-43D1-A5CD-DEC956F2BC2B
2018-03-28 03:41:38,839-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:41:38,840-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:41:47,664-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 067DDB7B-53E8-4420-8CAC-273509079E0A
2018-03-28 03:41:47,664-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:42:00,922-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A8099AE3-4627-4CAC-B480-76E21A523418
2018-03-28 03:42:00,922-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:42:26,271-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:42:26,271-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:45:03,231-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 03:45:03,404-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 03:45:03,516-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 03:45:03,562-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 03:50:08,474-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A0AEC20A-40C3-4417-902C-4AFE22EC3096
2018-03-28 03:50:08,474-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:50:11,211-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 207F2552-5EB5-49F9-B0D1-CB2B5FB9E97E
2018-03-28 03:50:42,067-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:50:42,067-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 03:50:44,601-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: C03C4ABC-DEFB-48BB-A557-AD06DF83A13C
2018-03-28 03:50:44,601-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:50:49,504-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 9AC27D7E-2FB1-4475-92E7-7AF17A69A275
2018-03-28 03:50:49,505-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 03:51:13,399-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 03:51:13,400-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:00:04,210-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 04:00:04,492-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 04:00:04,695-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 04:00:04,752-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 04:00:10,856-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 5C547A39-A1B8-4377-89F4-66B163E090E3
2018-03-28 04:00:10,856-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:00:13,909-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 54415E54-652B-4F9D-A135-366453326556
2018-03-28 04:00:45,976-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:00:45,977-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:00:48,677-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 7FC2A9B2-61A5-47DC-A8D8-AF64E844DE6C
2018-03-28 04:00:48,677-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:00:53,540-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 3C7AF46C-0A54-4BBB-AC18-D5F9A3C1C8BC
2018-03-28 04:00:53,540-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:01:18,120-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:01:18,121-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:10:08,349-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 27A6FA38-9F14-4393-8F7C-4C7B38898866
2018-03-28 04:10:08,349-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:10:11,068-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 31979525-8606-4EB8-AB51-0317BA220461
2018-03-28 04:10:41,004-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:10:41,005-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:10:43,661-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 069FC62D-E43D-43F1-8B9E-25A1583EBAF1
2018-03-28 04:10:43,661-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:10:49,337-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 86D5FD41-ECD4-48B3-82EB-2C9A844F24C6
2018-03-28 04:10:49,337-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:11:13,212-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:11:13,212-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:15:03,305-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 04:15:03,494-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 04:15:03,616-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 04:15:03,661-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 04:20:09,829-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: ECA71956-903D-4908-B188-6AFDEB0D0696
2018-03-28 04:20:09,829-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:20:12,503-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F4585691-1276-4E25-AD3A-706DB478E04C
2018-03-28 04:20:44,414-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:20:44,415-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:20:47,243-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 133C5951-0629-44F9-9A57-6FB81E5B79F8
2018-03-28 04:20:47,244-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:20:52,105-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 4F047BDA-CD3F-4DAB-8EB5-C009358C205E
2018-03-28 04:20:52,105-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:21:16,033-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:21:16,034-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:30:04,618-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 04:30:04,807-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 04:30:04,953-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 04:30:05,021-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 04:30:10,769-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 8FA70607-C309-4B87-B64A-8D060543F592
2018-03-28 04:30:10,770-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:30:15,189-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 60D81B63-2F96-4E6B-A6FF-D55A8AC96602
2018-03-28 04:30:51,168-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:30:51,169-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:30:55,688-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 028E599D-C284-4E8E-82E8-49455F6E65B6
2018-03-28 04:30:55,689-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:31:01,730-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 0466AAC8-AD5A-4599-9701-2477B35B161A
2018-03-28 04:31:01,730-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:31:28,445-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:31:28,446-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:40:09,738-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 480D6D42-F77E-4C20-BD92-32A03188B3D4
2018-03-28 04:40:09,739-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:40:12,934-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6977AAE1-4A10-4852-B8A4-18376B1B0894
2018-03-28 04:40:43,030-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:40:43,030-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:40:45,697-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 4AB55CED-FFDE-4B88-BD1C-14C6B7E9D4A7
2018-03-28 04:40:45,697-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:40:50,627-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F3B5C0D7-BB9B-4C15-B6D1-DC8CA1935E0D
2018-03-28 04:40:50,628-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:41:14,029-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:41:14,030-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:45:03,556-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 04:45:03,747-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 04:45:03,869-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 04:45:03,916-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 04:50:09,521-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: EB94DBCB-9F70-4560-94DC-E42E4B929D45
2018-03-28 04:50:09,521-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:50:12,969-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 733A703F-1C1A-432B-9F66-62B91D8CA517
2018-03-28 04:50:47,798-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:50:47,799-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 04:50:50,484-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 805490CE-0405-4E9C-B7DB-77BB984AA25D
2018-03-28 04:50:50,484-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:50:55,418-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: CDAD61E0-F284-43A9-8632-BCEF6FA650EE
2018-03-28 04:50:55,418-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 04:51:20,539-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 04:51:20,539-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:00:05,268-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 05:00:05,513-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 05:00:05,720-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 05:00:05,871-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 05:00:12,449-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 34C2DCB6-0886-4D0F-9804-8B839D4AD28C
2018-03-28 05:00:12,449-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:00:16,378-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: E1572DF5-5629-475E-92E1-5196546B6E3B
2018-03-28 05:00:48,289-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:00:48,290-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:00:50,968-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B2F21CA5-E0E1-462E-B85C-B3A10E3371E5
2018-03-28 05:00:50,969-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:00:55,830-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 0C6B59AB-B1E9-4AC3-B400-09AE7AFAE4DA
2018-03-28 05:00:55,831-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:01:21,039-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:01:21,040-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:10:08,434-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 03ED626A-33EF-44AF-AC72-8F443BAD9DA3
2018-03-28 05:10:08,434-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:10:11,192-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 58254D92-E70B-47E5-A0D3-829DC5CCEE79
2018-03-28 05:10:42,284-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:10:42,284-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:10:44,780-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E31B4E7E-CCC3-465C-9F61-751D72A632F6
2018-03-28 05:10:44,781-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:10:49,576-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B1E6995E-A2B5-49E2-A80F-2A10F880AF55
2018-03-28 05:10:49,576-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:11:13,454-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:11:13,454-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:15:03,156-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 05:15:03,349-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 05:15:03,475-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 05:15:03,523-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 05:20:08,919-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: AA59643F-1318-4F4E-B638-602F9CCB1F9A
2018-03-28 05:20:08,919-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:20:11,740-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4F942196-34EC-4C5C-8C29-6AD91C720D99
2018-03-28 05:20:43,090-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:20:43,091-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:20:45,684-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 420E5643-D2ED-4F24-9E92-4E1DF6B48802
2018-03-28 05:20:45,684-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:20:50,708-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 0CC46473-854D-4DAA-B873-9B15213EC1A9
2018-03-28 05:20:50,708-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:21:15,214-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:21:15,214-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:30:05,203-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 05:30:05,452-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 05:30:05,577-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 05:30:05,649-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 05:30:10,500-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A61CF045-D035-4E50-A150-270E84375AF1
2018-03-28 05:30:10,500-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:30:14,023-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6E50AABE-71C5-4752-9CC8-E69D077D3BE0
2018-03-28 05:30:45,182-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:30:45,183-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:30:47,787-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B88214F9-42D6-4D28-92C0-E9D53373E2BA
2018-03-28 05:30:47,787-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:30:52,991-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 494035D9-22B8-4544-A7A6-4840C028AB8D
2018-03-28 05:30:52,991-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:31:17,676-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:31:17,676-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:40:08,683-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 2D6BE0B0-3119-4497-9245-375525BB64FF
2018-03-28 05:40:08,683-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:40:12,173-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 857DF912-A814-422A-BBD7-1E783A345C21
2018-03-28 05:40:43,021-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:40:43,022-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:40:45,583-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: CE3220B6-CA46-4B54-A4CA-8BC8A432AD29
2018-03-28 05:40:45,583-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:40:50,380-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: D628D56A-59E8-4577-A114-EFA86D07AC2F
2018-03-28 05:40:50,380-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:41:13,555-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:41:13,555-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:45:02,828-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 05:45:03,021-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 05:45:03,141-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 05:45:03,193-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 05:50:09,921-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: FCDECA6B-F216-436F-B44A-337652E406F5
2018-03-28 05:50:09,922-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:50:12,591-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: D0F2BC65-DC5F-4453-8DE9-AF3EB73D73BA
2018-03-28 05:50:42,500-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:50:42,501-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 05:50:44,981-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 6FE838C3-D6DA-49BE-89BD-6C6BCF1EDE4B
2018-03-28 05:50:44,981-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:50:50,172-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: D40CBC98-8630-4FA2-9EFA-16B0ED427825
2018-03-28 05:50:50,172-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 05:51:14,103-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 05:51:14,103-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:00:04,422-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 06:00:04,702-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 06:00:04,970-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 06:00:05,038-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 06:00:11,863-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B82B1675-1106-4254-BE37-19F86031810D
2018-03-28 06:00:11,863-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:00:15,486-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: EEF2649D-032D-4D21-8062-6F96BBE727A8
2018-03-28 06:00:46,040-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:00:46,040-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:00:48,879-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 3BB79D1B-4953-46A0-8F46-22E09846F1D8
2018-03-28 06:00:48,879-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:00:54,041-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 56AFCD09-A23F-4A4F-91F6-EB9891CD499B
2018-03-28 06:00:54,041-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:01:20,239-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:01:20,240-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:10:08,878-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 87771369-6DD5-4175-9127-5F33990746E5
2018-03-28 06:10:08,878-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:10:11,870-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 71004467-8BCE-463D-8635-62AB92C87CAF
2018-03-28 06:10:41,881-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:10:41,882-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:10:44,395-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E73B4E40-888D-4F42-B832-EE7E2D396E0C
2018-03-28 06:10:44,396-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:10:49,400-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 1B0E7682-A4B5-4274-9327-AE8EB21F3F8D
2018-03-28 06:10:49,400-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:11:13,478-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:11:13,479-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:15:03,306-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 06:15:03,494-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 06:15:03,617-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 06:15:03,659-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 06:20:08,810-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: CA0BABD6-D43E-495D-8828-9492526C8B7A
2018-03-28 06:20:08,811-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:20:11,545-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 084D0F0C-82E1-4C1D-913D-BD8BF0F129FD
2018-03-28 06:20:42,044-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:20:42,044-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:20:44,777-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 55ED5637-040E-4197-B0E9-A85B4752A409
2018-03-28 06:20:44,777-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:20:49,776-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E6BFA9AF-E567-4589-8912-440D1A063567
2018-03-28 06:20:49,777-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:21:13,417-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:21:13,417-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:30:04,682-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 06:30:04,912-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 06:30:05,055-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 06:30:05,109-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 06:30:10,048-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: CB667F7A-0D29-43CA-AFE3-88975E915180
2018-03-28 06:30:10,048-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:30:12,978-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: CF164B3B-C9D8-420B-A5D1-B465A50D3CC4
2018-03-28 06:30:43,989-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:30:43,990-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:30:46,613-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 33C314B9-B954-415E-AFB8-69B954E38591
2018-03-28 06:30:46,613-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:30:51,634-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 81B2A680-00FC-47D3-8497-8BCC51AD2181
2018-03-28 06:30:51,634-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:31:17,981-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:31:17,982-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:40:08,406-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 17521A80-2744-4F78-8921-1ECB5C67CEB5
2018-03-28 06:40:08,407-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:40:11,403-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 5575006D-AC4F-49AB-B097-950B92695634
2018-03-28 06:40:41,333-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:40:41,334-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:40:43,782-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E4842C42-A3EF-4AB4-84C2-FAB468648FCB
2018-03-28 06:40:43,783-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:40:48,673-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 93BCFC8A-FC78-4EB1-B923-D40BEF6A4990
2018-03-28 06:40:48,674-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:41:12,361-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:41:12,362-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:45:02,775-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 06:45:02,951-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 06:45:03,072-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 06:45:03,123-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 06:50:08,737-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 8DA94FF0-20D6-4109-86EA-B0F90AB69750
2018-03-28 06:50:08,738-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:50:11,821-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4E8B1952-FB25-4772-9497-E170514A0452
2018-03-28 06:50:42,494-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:50:42,494-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 06:50:45,035-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 9E06621E-9105-4C7F-B52D-BDAACCF8D014
2018-03-28 06:50:45,035-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:50:50,196-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B3F1F401-F5D7-43A8-8018-65EC6573359D
2018-03-28 06:50:50,196-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 06:51:15,089-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 06:51:15,090-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:00:04,669-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 07:00:04,971-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 07:00:05,113-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 07:00:05,163-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 07:00:10,464-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: BE828622-0466-4B17-A356-CD539DCFF59F
2018-03-28 07:00:10,464-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:00:13,297-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 0D629F5E-7D29-40A2-9B34-0A4B57EA1527
2018-03-28 07:00:45,549-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:00:45,550-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:00:48,382-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: AD36C261-5273-4F5F-9268-494C53A83DCE
2018-03-28 07:00:48,382-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:00:53,523-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 84AB5CE1-BB79-46CD-914D-C84887195FF2
2018-03-28 07:00:53,523-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:01:17,390-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:01:17,390-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:10:08,078-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 931BCC7D-B497-4F84-AA5C-B77B905C7226
2018-03-28 07:10:08,078-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:10:10,844-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 347F1ACE-1299-40EB-BAF1-21D15589B66C
2018-03-28 07:10:42,288-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:10:42,288-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:10:45,147-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 09A52DBE-5B5E-4BFD-AFFB-7C880A3AB1B7
2018-03-28 07:10:45,147-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:10:50,289-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: C3867051-3688-4D34-91D7-CAD3B6650926
2018-03-28 07:10:50,289-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:11:14,956-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:11:14,957-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:15:03,038-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 07:15:03,227-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 07:15:03,383-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 07:15:03,428-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 07:20:08,954-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 221A789B-DB00-4D57-94AE-14ADC1F567CC
2018-03-28 07:20:08,954-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:20:11,707-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: C41C984A-BF7F-4DC3-8295-AF670367B171
2018-03-28 07:20:42,956-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:20:42,957-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:20:45,757-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: C594CB16-C551-41DB-8D84-AFFB7C60F41B
2018-03-28 07:20:45,757-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:20:50,805-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B364DE32-4CDA-4C05-8CAA-86F52B1F220E
2018-03-28 07:20:50,805-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:21:15,960-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:21:15,961-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:30:04,369-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 07:30:04,672-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 07:30:05,011-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 07:30:05,096-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 07:30:09,500-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: DB987A46-659B-47E6-AA21-056E65000786
2018-03-28 07:30:09,500-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:30:12,324-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: D6BC5EB9-4FDA-48D3-B61A-79120B949386
2018-03-28 07:30:43,982-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:30:43,982-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:30:46,546-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F66A797F-B8EE-4F3D-BDDB-CAD1F87218DC
2018-03-28 07:30:46,546-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:30:51,380-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 084B5CD2-DCBC-455E-9F11-E94C01CE5212
2018-03-28 07:30:51,380-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:31:15,872-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:31:15,873-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:40:09,648-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 7DFC3E0B-23DA-4EFB-A844-E31A44B57BDA
2018-03-28 07:40:09,648-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:40:12,509-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6E3B4B3A-09EF-4961-B9BB-BF6163E6B02E
2018-03-28 07:40:42,908-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:40:42,908-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:40:45,424-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 1962AFE8-1048-48CA-9FB9-DBB71A4DA2E4
2018-03-28 07:40:45,425-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:40:50,443-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F9200060-040C-43B2-BE77-87447516A441
2018-03-28 07:40:50,443-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:41:15,696-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:41:15,697-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:45:03,398-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 07:45:03,616-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 07:45:03,748-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 07:45:03,812-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 07:50:08,801-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 2546A60A-4C13-4533-A55B-50C9F0CFEA54
2018-03-28 07:50:08,801-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:50:11,910-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 67F27D85-8F71-48DC-9752-1CAB4068CFEB
2018-03-28 07:50:45,989-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:50:45,989-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 07:50:48,585-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: FC5621E8-E333-4A08-ADC7-AD53F71A5A71
2018-03-28 07:50:48,586-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:50:53,464-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 04511528-2C9F-483E-B4BD-441A8D316218
2018-03-28 07:50:53,464-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 07:51:18,094-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 07:51:18,094-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:00:04,986-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 08:00:05,302-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 08:00:05,545-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 08:00:05,591-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 08:00:10,929-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 2CE2A613-7D64-4954-8DA9-556CA6F3245B
2018-03-28 08:00:10,930-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:00:14,128-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: FB1B7957-3E8A-4239-BFA2-62AA200C669C
2018-03-28 08:00:45,423-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:00:45,424-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:00:48,007-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 3F43D87A-0DD6-4141-BAEE-0D46A15B7938
2018-03-28 08:00:48,007-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:00:53,552-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 648F1C51-D508-4F23-A81C-4D93EC734396
2018-03-28 08:00:53,552-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:01:01,231-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 500 Error:InternalError The request processing has failed due to some unknown error, exception or failure. RequestID: 564FB3F3-5251-4E74-8C79-7604A5B1A00B
2018-03-28 08:01:01,232-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.49 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:01:18,112-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:01:18,112-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:10:09,466-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 81803784-347D-4DD4-AC62-6B3492B07725
2018-03-28 08:10:09,466-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:10:12,331-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 29245923-DE72-44AD-8C88-41C4C06126B9
2018-03-28 08:10:43,053-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:10:43,054-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:10:45,609-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: CF2FAF8C-65B7-4436-B3EE-5350134AED3A
2018-03-28 08:10:45,609-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:10:50,614-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: BF1E0757-1E3D-48ED-A8E0-7A466A136746
2018-03-28 08:10:50,614-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:11:15,125-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:11:15,126-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:15:02,996-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 08:15:03,205-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 08:15:03,338-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 08:15:03,383-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 08:20:09,313-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A87BCB1F-6E6F-4E6C-8588-44A53729C558
2018-03-28 08:20:09,314-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:20:12,288-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: B398024A-9E12-4F8A-B686-F9393C1C653D
2018-03-28 08:20:43,400-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:20:43,400-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:20:46,120-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: C314370D-F60B-4FDF-BE9D-5A931BD1B62D
2018-03-28 08:20:46,120-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:20:51,408-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A97E195F-2464-49E7-9E3A-430C47ABE938
2018-03-28 08:20:51,409-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:21:15,679-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:21:15,679-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:30:05,136-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 08:30:05,449-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 08:30:05,611-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 08:30:05,654-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 08:30:11,637-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 30EB91DB-3798-483F-A813-8989E75544E7
2018-03-28 08:30:11,637-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:30:14,374-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 47AB7E5A-0D45-4390-BF83-CD5147D23615
2018-03-28 08:30:44,875-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:30:44,875-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:30:47,509-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 599B163F-5A38-46BD-964D-22DA4459BF04
2018-03-28 08:30:47,509-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:30:52,549-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 6951D582-466B-4CCB-8F7D-85FAD587DA75
2018-03-28 08:30:52,550-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:31:16,732-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:31:16,732-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:40:08,643-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: C03A160D-7400-4942-A2DE-9A04B647B1A8
2018-03-28 08:40:08,643-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:40:11,503-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: B53BB559-002E-4607-9DE5-4B009815AA40
2018-03-28 08:40:42,818-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:40:42,818-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:40:45,361-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 1A8C3196-6940-47D4-A077-FE8DCEE88E9B
2018-03-28 08:40:45,361-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:40:50,346-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 464932AB-121F-4188-BC1A-D5BE654110AC
2018-03-28 08:40:50,347-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:41:15,055-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:41:15,055-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:45:03,374-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 08:45:03,569-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 08:45:03,704-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 08:45:03,750-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 08:50:08,625-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 36823746-E2EB-4C64-B11F-B673CBB58BCC
2018-03-28 08:50:08,626-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:50:11,472-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 4B24B99C-8265-496A-8AFD-C9C0B66AAFCD
2018-03-28 08:50:43,366-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:50:43,367-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 08:50:46,037-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: DAA48643-7A28-4721-A262-00A50615243F
2018-03-28 08:50:46,037-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:50:51,229-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A89569D2-2386-44C2-8A76-3FC3734FE45D
2018-03-28 08:50:51,229-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 08:51:15,657-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 08:51:15,657-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:00:04,980-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 09:00:05,250-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 09:00:05,370-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 09:00:05,433-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 09:00:11,226-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: FC4CFDE7-B4E2-41DF-B215-C33CF92C8557
2018-03-28 09:00:11,226-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:00:14,138-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F0A8A02C-C1CA-4650-86E6-82828D8EC315
2018-03-28 09:00:47,436-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:00:47,436-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:00:50,081-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 7B945CB5-EA5B-4A6B-9359-5E99BEFF8999
2018-03-28 09:00:50,081-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:00:55,287-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F8D51EC0-70CF-4F63-AA63-2FA5D0691CA2
2018-03-28 09:00:55,288-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:01:21,174-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:01:21,175-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:10:10,515-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 14C88A06-7AFA-49E5-A5D2-B5BFB4D60353
2018-03-28 09:10:10,515-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:10:14,253-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: F7570691-2800-43F9-8351-7A5B7B484080
2018-03-28 09:10:45,433-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:10:45,434-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:10:48,403-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F02FC9D2-9035-4E0F-A176-076CADBA3285
2018-03-28 09:10:48,404-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:10:53,683-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 53C7BEC5-D25E-4080-A659-D21C78F31022
2018-03-28 09:10:53,683-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:11:19,779-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:11:19,779-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:15:02,992-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 09:15:03,178-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 09:15:03,311-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 09:15:03,360-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 09:20:09,305-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B67E3312-61AE-4E46-9D5C-6A58C6E4CAA5
2018-03-28 09:20:09,305-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:20:12,666-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 0BE64C2E-F457-4324-92E1-A37FBE975EA7
2018-03-28 09:20:44,285-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:20:44,286-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:20:46,943-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 7D664881-AFBE-4E5D-A3E5-75D3119801E2
2018-03-28 09:20:46,943-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:20:52,246-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 5CEF4D4F-E23E-41C8-9B22-70DEEDC2B9E0
2018-03-28 09:20:52,246-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:21:20,458-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:21:20,458-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:30:05,399-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 09:30:05,594-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 09:30:05,747-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 09:30:05,801-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 09:30:10,921-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: EC405D02-C69E-41FA-8802-F9E5B8F3924D
2018-03-28 09:30:10,921-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:30:13,985-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 99F93318-FF11-4F95-9971-DF222B67242D
2018-03-28 09:30:51,004-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:30:51,004-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:30:53,664-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: B23D611C-E6F9-44A1-B491-0BD1A79F021A
2018-03-28 09:30:53,664-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:30:58,936-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 2B5C6291-FE93-47A9-BF1E-9E72FD0B715E
2018-03-28 09:30:58,937-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:31:23,790-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:31:23,791-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:40:09,160-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 0B5DBA96-DB95-4035-8447-7F0A5DBA9366
2018-03-28 09:40:09,161-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:40:12,101-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 44A91F9C-B3DF-4E17-BDE6-88CF10AD57C2
2018-03-28 09:40:45,241-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:40:45,242-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:40:48,158-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 6DFCC8A7-0F61-4913-B283-B3D1B906DBB0
2018-03-28 09:40:48,158-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:40:53,300-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 8C063749-C653-4F1D-893D-B1646643FBA0
2018-03-28 09:40:53,301-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:41:18,062-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:41:18,063-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:45:03,335-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 09:45:03,544-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 09:45:03,679-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 09:45:03,729-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 09:50:10,527-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E8E68833-2C82-4DFA-BA7F-C2FF9F4D57E4
2018-03-28 09:50:10,528-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:50:13,879-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: FA6E72D7-0ADA-4606-9D72-54EE3A563D1F
2018-03-28 09:50:45,373-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:50:45,373-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 09:50:48,084-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: D4301701-DC12-46F5-BB1C-524905271EB2
2018-03-28 09:50:48,084-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:50:52,932-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: ECAB6855-A456-48AA-B942-1214DCDA1F50
2018-03-28 09:50:52,932-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 09:51:17,485-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 09:51:17,485-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:00:04,631-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 10:00:04,841-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 10:00:04,982-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 10:00:05,074-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 10:00:10,705-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 7C2E4B05-87CC-4DA0-891C-A49EF6E5832B
2018-03-28 10:00:10,705-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:00:13,702-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6248E60C-EE1C-46A9-BDD2-25809A247B1E
2018-03-28 10:00:45,169-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:00:45,170-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:00:48,009-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 90F999D8-DC59-4FF3-AB78-629FE17A6188
2018-03-28 10:00:48,009-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:00:53,364-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F3FE0009-A729-4B3B-BAF0-1FE7D2B39481
2018-03-28 10:00:53,364-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:01:18,567-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:01:18,568-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:17:16,143-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:470]-服务器 10.82.40.82 在 zabbix 中不存在
2018-03-28 10:17:16,158-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:470]-服务器 10.82.40.77 在 zabbix 中不存在
2018-03-28 10:17:16,177-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:470]-服务器 10.82.40.81 在 zabbix 中不存在
2018-03-28 10:17:16,195-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:470]-服务器 10.82.40.76 在 zabbix 中不存在
2018-03-28 10:17:16,200-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:470]-服务器 10.82.40.75 在 zabbix 中不存在
2018-03-28 10:17:16,205-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:470]-服务器 10.82.40.79 在 zabbix 中不存在
2018-03-28 10:20:09,303-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F7898B90-7150-4CF5-A921-B677A558E294
2018-03-28 10:20:09,303-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:20:12,373-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 0E8756B0-00E8-4957-A64D-C6EE0F6B3DE2
2018-03-28 10:20:46,405-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:20:46,405-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:20:49,028-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: F6D9EB3F-924F-46FB-9228-AF45839FE36C
2018-03-28 10:20:49,028-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:20:54,424-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: D9D01B26-CEA5-4B93-A7AC-AAC3D1845DD3
2018-03-28 10:20:54,425-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:21:19,875-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:21:19,876-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:30:05,453-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.86 实例名 mysql1 格式不正确
2018-03-28 10:30:05,845-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.24 实例名 webproxytoidc 格式不正确
2018-03-28 10:30:05,989-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.90 实例名 mysql3 格式不正确
2018-03-28 10:30:06,032-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:96]-该服务器: 172.17.134.89 实例名 mysql2 格式不正确
2018-03-28 10:30:12,142-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 52BF3648-8DD9-42C6-9571-D56AE0917EC1
2018-03-28 10:30:12,143-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:30:15,131-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 8DF84B64-D158-4740-8202-F826F97DA60D
2018-03-28 10:30:47,103-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:30:47,103-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:30:49,756-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A535D522-4E3E-49CF-82EA-07A13FE81512
2018-03-28 10:30:49,756-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:30:55,056-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: A1B2AFF1-F3F6-48C4-B15D-A4CB1CD97F79
2018-03-28 10:30:55,057-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:31:20,298-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:31:20,299-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:40:09,401-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: 14938015-AED3-48DD-BD40-C695198051E4
2018-03-28 10:40:09,402-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.86 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:40:12,290-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:ChargeTypeViolation Pay-As-You-Go instances do not support this operation. RequestID: 6A61FB3B-F766-4414-A957-7ED32F7BB238
2018-03-28 10:40:45,052-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:40:45,053-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.122 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
2018-03-28 10:40:47,869-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: ED42B0E3-5F5B-4711-97B1-BE1EA3F3BAAC
2018-03-28 10:40:47,869-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.90 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:40:52,889-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/api/thirdapi/aliyun_describe_instance.py-[line:67]-HTTP Status: 403 Error:IncorrectInstanceStatus The current status of the resource does not support this operation. RequestID: E9D4CAFB-2D38-4DC4-85CC-DB3B40B2A0C8
2018-03-28 10:40:52,889-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.134.89 自动刷新失败,错误信息: aliyun api 获取续费状态失败，请查看日志
2018-03-28 10:41:19,277-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/server/__init__.py-[line:85]-("'ResultCallback' object has no attribute 'data'",)
2018-03-28 10:41:19,277-[ERROR]-/ops-data/zp/haha/mysite-11/opsweb/resources/cron.py-[line:33]-服务器: 172.17.92.123 自动刷新失败,错误信息: ansible api 调用失败，请查看日志
